spring:
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: dummy
          uri: http://localhost:8080
          predicates:
            - Path=/dummyService/**
          filters:
            - RewritePath=/dummyService/(?<segment>.*), /dummy/$\{segment}
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward:/fallback

        - id: fallback
          uri: http://localhost:8081
          predicates:
              - Path=/fallback
          filters:
            - name: FallbackHeaders
            - AddRequestHeader=X-Request-Server,core



resilience4j:
  circuit-breaker:
    configs:
      default:
        minimumNumberOfCalls: 1
        failureRateThreshold: 1
        waitDurationInOpenState: 10s
        slowCallRateThreshold: 10
        slowCallDurationThreshold: 5s
        permittedNumberOfCallsInHalfOpenState: 1


server:
  port: 8080
