spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: dummy
          uri: http://localhost:8080
          predicates:
            - Path=/dummyService/**
          filters:
            - RewritePath=/dummyService/(?<segment>.*), /dummy/$\{segment}
            - name: CircuitBreaker
              args:
                name: circuit-breaker
                fallbackUri: forward:/fallback

        - id: fallback
          uri: http://localhost:8081
          predicates:
              - Path=/fallback
          filters:
            - name: FallbackHeaders
            - AddRequestHeader=X-Request-Server,core

eureka:
  instance:
    instance-id: GATEWAY
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

resilience4j:
  circuit-breaker:
    configs:
      default:
        minimumNumberOfCalls: 1
        failureRateThreshold: 1
        waitDurationInOpenState: 10s
        slowCallRateThreshold: 10
        slowCallDurationThreshold: 5s
        permittedNumberOfCallsInHalfOpenState: 1


server:
  port: 8080

management:
  endpoints:
    jmx:
      exposure:
        include: refresh, health, beans
    web:
      exposure:
        include: "*"
  health:
    circuit-breakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    resume.enabled: true
    pause.enabled: true
    restart.enabled: true
    shutdown.enabled: false