server:
  port: 8761

spring:
  application:
    name: DISCOVERY
  profiles:
    active: dev

eureka:
  server:
    enable-self-preservation: true
  instance:
    registry:
      default-open-for-traffic-count: 0
    instance-id: DISCOVERY
    hostname: DISCOVERY
    ip-address: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"