spring:
  application:
    name: service-a
  profiles:
    active: dev

server:
  port: 8089

eureka:
  instance:
    instance-id: service-a:${server.port}
    hostname: service-a
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    resume.enabled: true
    pause.enabled: true
    restart.enabled: true
    shutdown.enabled: false