spring:
  application:
    name: FALLBACK
  profiles:
    active: dev

server:
  port: 8081

eureka:
  instance:
    instance-id: fallback
    hostname: fallback
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    jmx:
      exposure:
        include: refresh, health, beans
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
    resume.enabled: true
    pause.enabled: true
    restart.enabled: true
    shutdown.enabled: false